StretchCeilingProject/Models/CeilingModel.cs
using System;

namespace StretchCeilingProject.Models
{
    public class CeilingModel
    {
        public Guid ImageId { get; set; }
        public float Cost { get; set; }
        public string Description { get; set; }
    }
}

StretchCeilingProject/Controllers/CellingDetailsController.cs
using StretchCeilingProject.BLL;
using StretchCeilingProject.Entity;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace StretchCeilingProject.Controllers
{
    public class CellingDetailsController : Controller
    {
        public CellingDetailsController(ICellingLogic cellingLogic)
        {
            this.CellingLogic = cellingLogic;
        }

        private ICellingLogic CellingLogic { get; }

        public ActionResult Index(Guid id)
        {
            Celling c = this.CellingLogic.Get(id);
            CellingDescription cellingDescription = this.CellingLogic.GetDescription(id);

            return View(new KeyValuePair<string, CellingDescription>(c.Title, cellingDescription));
        }
    }
}

StretchCeilingProject/Controllers/ErrorController.cs
using System.Web.Mvc;

namespace StretchCeilingProject.Controllers
{
    public class ErrorController : Controller
    {
        public ActionResult Index()
        {
            Response.StatusCode = 400;
            return View();
        }

        public ActionResult Error404()
        {
            Response.StatusCode = 404;
            return View();
        }
    }
}

StretchCeilingProject/Controllers/HomeController.cs
using StretchCeilingProject.BLL;
using StretchCeilingProject.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace StretchCeilingProject.Controllers
{
    public class HomeController : Controller
    {
        public HomeController(ICellingLogic cellingLogic)
        {
            this.CellingLogic = cellingLogic;
        }

        private ICellingLogic CellingLogic { get; }

        public ActionResult Contacts()
        {
            return View();
        }

        public ActionResult Index()
        {
            IEnumerable<IGrouping<CellingCategory, Celling>> goods = this.CellingLogic.GetGroupedByCategory();

            return View(goods);
        }

        public ActionResult Price()
        {
            IEnumerable<IGrouping<CellingCategory, Celling>> goods = this.CellingLogic.GetGroupedByCategory();

            return View(goods);
        }

        public ActionResult Reviews()
        {
            return View();
        }
    }
}

StretchCeilingProject/Controllers/ImageController.cs
using StretchCeilingProject.BLL;
using StretchCeilingProject.Common;
using StretchCeilingProject.Entity;
using System;
using System.Diagnostics.Contracts;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace StretchCeilingProject.Controllers
{
    public class ImageController : Controller
    {
        public ImageController(ImageLogic imageLogic)
        {
            this.ImageLogic = imageLogic;
        }

        private ImageLogic ImageLogic { get; }

        [HttpPost]
        public EmptyResult Add(HttpPostedFileBase file)
        {
            Contract.Requires<ArgumentNullException>(file != null, "Image content can not be null");
            Contract.Requires<InvalidOperationException>(file.ContentLength > 0, "Image content is too small");

            byte[] array;

            using (MemoryStream ms = new MemoryStream())
            {
                file.InputStream.CopyTo(ms);
                array = ms.GetBuffer();
            }

            Image image = new Image(array);

            this.ImageLogic.Add(image);

            return new EmptyResult();
        }

        [HttpGet]
        public ActionResult Get(Guid? imageId)
        {
            Contract.Requires<ArgumentNullException>(imageId.HasValue, "Image id can not be null");
            Contract.Requires<InvalidOperationException>(imageId.Value != default(Guid), "Image id can not be default");

            Image content = this.ImageLogic.Get(imageId.Value);

            return new FileContentResult(content.Content, Constant.MIMEType)
            {
                FileDownloadName = imageId.ToString()
            };
        }
    }
}

StretchCeilingProject/Views/CellingDetails/Index.cshtml
@model KeyValuePair<string, StretchCeilingProject.Entity.CellingDescription>

@{
    ViewBag.Title = "СтройТрест - натяжные потолки - подробнее о потолке";
    ViewBag.Description = "СтройТрест Строй Трест - описание потолка, картинки потолка, ремонт в квартире в Саратове";
    Layout = "~/Views/Layouts/DefaultLayout.cshtml";
}

<div class="centred cellingDescriptionAsd">@Model.Key</div>

<div class="col-xs-12">
    <p >@Model.Value.Description</p>

    <h2 class="centred cellingDescriptionTitle">Его сильные стороны</h2>

    <ul class="advantages">
        @foreach (var item in Model.Value.Procs)
        {
            <li>@item</li>
        }
    </ul>

    <h3>Примеры работ</h3>

    @foreach (var imageId in Model.Value.ImageIds)
    {
        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="celling">
                <img src="@imageId" alt="cellingImage" />
            </div>
        </div>
    }
</div>

StretchCeilingProject/Views/Home/Contacts.cshtml
@{
    ViewBag.Title = "СтройТрест - натяжные потолки - контакты";
    ViewBag.Description = "СтройТрест Строй Трест - контакты с компанией, телефон, почта, позвонить";
    Layout = "~/Views/Layouts/DefaultLayout.cshtml";
}

<h2>Контакты</h2>

<div class="col-xs-12">
    <div>Телефон: +7-919-825-25-84</div>
    <div>Почта: ko4299@yandex.ru</div>
</div>  

StretchCeilingProject/Views/Home/Index.cshtml
@using StretchCeilingProject.Common
@using StretchCeilingProject.Entity
@model IEnumerable<IGrouping<CellingCategory, Celling>>
@{
    ViewBag.Title = "СтройТрест - натяжные потолки";
    ViewBag.Description = "СтройТрест Строй Трест - продажа натяжных потолков, создание натяжных потолков, заказать потолок, ремонт квартиры в Саратове, главная страница";
    Layout = "~/Views/Layouts/DefaultLayout.cshtml";
}

<article class="col-xs-12">
    <h2 class="centred">Натяжные потолки в Саратове и Энгельсе.</h2>

    <p>Наша компания предлагает услуги по монтажу натяжных потолков известных европейских и отечественных производителей в Саратове, Энгельсе и области. У нас вы найдете широчайший ассортимент.</p>
    <p>Трудно сделать выбор? Наши специалисты помогут, детально рассказав о достоинствах и особенностях каждого материала, фактуры, цветовой гаммы.</p>

    <h3>Наши основные преимущества:</h3>
    <ul class="advantages">
        <li>Минимальные сроки изготовления заказа</li>
        <li>Доступные цены – от 250 ₽ кв.м</li>
        <li>качество</li>
        <li>широкий выбор цветов и фактур</li>
        <li>монтажники с многолетним опытом</li>
        <li>Бесплатный замер и быстрота расчета стоимости  - за 10 мин</li>
        <li>индивидуальный подход к каждому клиенту</li>
    </ul>
</article>

@foreach (var pair in Model)
{
    if (pair.Key == CellingCategory.Celling)
    {
        foreach (var celling in pair)
        {
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="celling spaceFlex" style="background-image: url(@celling.ImageUrl);">
                    <h3 class="cellingTitle .one-line-max">
                        @Html.ActionLink(celling.Title, "Index", "CellingDetails", new { Id = celling.Id }, null)
                    </h3>
                    <div class="cellingCost">
                        <span>@celling.Cost</span>
                    </div>
                    <div class="cellingDescription two-lines-max">
                        <span>@celling.Description</span>
                        <div class="moredots">
                            <span>...</span>
                            <span class="tip">@Html.ActionLink("Подробнее...", "Index", "CellingDetails", new { Id = celling.Id }, null)</span>
                        </div>
                    </div>
                </div>
            </div>
        }

        <div class="col-xs-12 examples">
            <h3>Наши работы</h3>

            @foreach (var imageUrl in Constant.OurWorkImagesUrls)
            {
                <div class="item col-sm-6 col-xs-12">
                    <img src="@imageUrl" alt="ourWorkImage">
                </div>
            }
        </div>
    }
}

StretchCeilingProject/Views/Home/Price.cshtml
@using StretchCeilingProject.Common
@using StretchCeilingProject.Entity
@model IEnumerable<IGrouping<StretchCeilingProject.Entity.CellingCategory, StretchCeilingProject.Entity.Celling>>

@{
    ViewBag.Title = "СтройТрест - натяжные потолки - цены";
    ViewBag.Description = "СтройТрест Строй Трест - цены на потолки, ремонт потолка в Саратове, заказ потолка";
    Layout = "~/Views/Layouts/DefaultLayout.cshtml";
}

<h2>Price</h2>

<article class="col-xs-12">
    <ul class="nav nav-tabs cellings" role="tablist" id="myTabExample">
        @foreach (var pair in Model)
        {
            if (pair.Key == CellingCategory.Celling)
            {
                continue;
            }

            <li><a href="#@pair.Key" role="tab" data-toggle="tab">@pair.Key.GetName()</a></li>
        }
    </ul>

    <div class="tab-content ">
        @foreach (var pair in Model)
        {
            if (pair.Key == CellingCategory.Celling)
            {
                continue;
            }

            <div class="tab-pane active row" id="@pair.Key">
                @if (pair.Key == CellingCategory.Another ||
                    pair.Key == CellingCategory.Construction)
                {
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Ед.изм.</th>
                            <th>Стоимость (₽)</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var celling in pair)
                        {
                            <tr>
                                <td>@celling.Title</td>
                                <td>@celling.Description</td>
                                <td>@celling.Cost</td>
                            </tr>
                        }
                        </tbody>
                    </table>
                }
            </div>

        }
    </div>
</article>

StretchCeilingProject/Views/Home/Reviews.cshtml
@{
    ViewBag.Title = "СтройТрест - натяжные потолки - отзывы";
    ViewBag.Description = "СтройТрест Строй Трест - отзывы о компании, качество работ, хороший ремонт, недорогой ремонт";
    Layout = "~/Views/Layouts/DefaultLayout.cshtml";
}

<h2>Reviews</h2>

StretchCeilingProject/Views/Layouts/DefaultLayout.cshtml
@using StretchCeilingProject.Common
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="yandex-verification" content="e68c1e91130def8e" />
    <meta name="description" content="@ViewBag.Description" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/colorTheme.css" rel="stylesheet" />
    <link href="~/Content/commonStyleSheet.css" rel="stylesheet" />
</head>
<body>

    <header class="col-lg-8 col-lg-offset-2 col-md-12 clearfix">
        <nav class="navbar navbar-default">
            <div class="centred callme">
                <span>ВЫЗОВ ЗАМЕРЩИКА</span>
                <img src="https://psv4.vk.me/c810133/u50666290/docs/e5f6fe4f8f47/zvonok.png" alt="callImage" />
            </div>

            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">СтройТрест</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li data-name="Index">@Html.ActionLink("Главная", "Index", "Home")</li>
                        <li data-name="Price">@Html.ActionLink("Цены", "Price", "Home")</li>
                        <li data-name="Contacts">@Html.ActionLink("Контакты", "Contacts", "Home")</li>
                        <li data-name="Contacts">@Html.ActionLink("Отзывы", "Reviews", "Home")</li>
                    </ul>
                    <a class="navbar-brand" style="float: right" href="#">Телефон: +7-919-825-25-84</a>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </header>

    <div class="col-lg-8 col-lg-offset-2 col-md-12 hidden-xs clearfix">

        <h1 class="marquee"><span>НАТЯЖНЫЕ ПОТОЛКИ от 250 кв.м</span></h1>

        <div id="myCarousel" class="carousel" data-rimageIde="carousel">
            <!-- Wrapper for slimageIdes -->
            <div class="carousel-inner" role="listbox">

                @foreach (var imageUrl in Constant.CarouselImagesUrls)
            {
                    <div class="item col-xs-6 col-xs-offset-3">
                        <img src="@imageUrl" alt="carouselImage">
                    </div>
                }
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slimageIde="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-himageIdden="true"></span>
                <span class="sr-only">Previous</span>
            </a>

            <a class="right carousel-control" href="#myCarousel" role="button" data-slimageIde="next">
                <span class="glyphicon glyphicon-chevron-right" aria-himageIdden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <article class="col-lg-8 col-lg-offset-2 col-md-12 clearfix">
        @RenderBody()
    </article>

    @*@using (Html.BeginForm("Add", "Image", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="file" />

            <input type="submit" value="Go" />
        }*@

    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/commonJavaScript.js"></script>
</body>
</html>